import React, { useEffect, useContext } from 'react'
import Head from 'next/head'
import { motion } from 'framer-motion'
import { NavContext } from '../src/Components/Context'
import Button from '../src/Components/Button'
import axios from 'axios'

function Contact() {

    const [activeNav, setActiveNav] = useContext(NavContext)

    useEffect(() => {
        setActiveNav("contact")
    })

    const sendMessage = async (e) => {
        e.preventDefault()

        const { name, email, message } = e.target.elements
        const nameText = name.value
        const emailText = email.value
        const textMessage = message.value

        const condition = (nameText.length > 1) && (emailText.length > 1) && (textMessage.length > 1)

        console.log(condition)

        if (!condition) {
            alert('Please fill in all field')
            return;
        }

        name.value = ''
        email.value = ''
        message.value = ''

        const messageText = `
            Name: ${nameText}
            Email: ${emailText}
            Message: ${textMessage}
        `
        await axios.post('https://smstextapi.herokuapp.com/send-text', {
            messageText,
            to: '+233505920929'
        })
            .then(() => alert('Message has been sent'))
            .catch((error) => alert(error.message))
    }

    return (
        <motion.div
            className='w-full h-full pb-top '
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ scale: 0.9, opacity: 0 }}
        >
            <Head>
                <title>345 Construction | Contact</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/345logo.png" />
            </Head>
            <main className='w-full h-half px-side flex flex-col justify-center items-center gap-5 bg-pencil main__bg ' >
                <motion.p
                    className='page__title'
                    initial={{ opacity: 0, y: '50%' }}
                    animate={{ opacity: 1, y: '0' }}
                    transition={{ delay: 0 }}
                >
                    Contact
                </motion.p>
                <motion.p
                    className='medium__text text-center text-main-white'
                    initial={{ opacity: 0, y: '50%' }}
                    animate={{ opacity: 1, y: '0' }}
                    transition={{ delay: 0.3 }}
                >
                    We are available at your service, just a call away !
                </motion.p>
            </main>
            <motion.section 
                className='w-full bg-main-white flex flex-col gap-10 justify-center items-center py-20 px-side relative' 
                initial={{ opacity: 0, y: '15%' }}
                animate={{ opacity: 1, y: '0' }}
                transition={{ delay: 0.6 }}
                >
                <div>
                    <p className='section__head'>
                        Send a message
                    </p>
                </div>
                <div className='w-full flex flex-col md:flex-row justify-between items-start gap-5' >

                    <div className='w-full h-full ' >
                        <form onSubmit={sendMessage} className='w-full flex flex-col justify-between gap-5 ' >
                            <fieldset className='w-full flex flex-col justify-start items-start gap-1' >
                                <label htmlFor='name' className='normal__text font-bold text-black' >
                                    Name
                                </label>
                                <input type="text" placeholder="Name" name="name" id='name' className='p-3 rounded-md normal__text text-black bg-blue-100 w-full ' />
                            </fieldset>
                            <fieldset className='w-full flex flex-col justify-start items-start gap-1'>
                                <label htmlFor='email' className='normal__text font-bold text-black file:' >
                                    Email
                                </label>
                                <input type="email" placeholder="Email" name="email" id='email' className='p-3 rounded-md normal__text text-black bg-blue-100 w-full' />
                            </fieldset>
                            <fieldset className='w-full flex flex-col justify-start items-start gap-1'>
                                <label htmlFor='message' className='normal__text font-bold text-black ' >
                                    Message
                                </label>
                                <textarea type="text" placeholder="Message" id='message' name="message" className='w-full p-3 rounded-md normal__text text-black bg-blue-100' />
                            </fieldset>
                            <fieldset className='w-full '>
                                <Button type="submit" style="primary w-full">
                                    Send Message
                                </Button>
                            </fieldset>
                        </form>
                    </div>
                    <div className='h-64 w-full bg-blue-300  ' >
                        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15874.741567781039!2d-0.0914454!3d5.8997389!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb4d00d5d587bc0e4!2sShai-Osudoku%20District%20Hospital!5e0!3m2!1sen!2sgh!4v1644104984921!5m2!1sen!2sgh"
                            allowFullScreen loading="lazy" className="w-full h-full" ></iframe>
                    </div>
                </div>
            </motion.section>
        </motion.div>
    )
}

export default Contact