import { useContext, useEffect, useState } from 'react'
import { useInView } from 'react-intersection-observer'
import { motion, useAnimation } from 'framer-motion'
import Head from 'next/head'
import axios from 'axios'
import AdvantageCard from '../src/Components/AdvantageCard'
import Button from '../src/Components/Button'
import ProjectCard from '../src/Components/ProjectCard'
import ServiceCard from '../src/Components/ServiceCard'
import { NavContext } from '../src/Components/Context'
import home from '../public/home.jpg'
import house from '../public/house.jpg'
import real from '../public/real-house.jpg'
import AnchorLink from '../src/Components/AnchorLink'

export default function Home() {


  const [loading, setLoading] = useState(false)

  const [activeNav, setActiveNav] = useContext(NavContext)

  const { ref, inView } = useInView({
    threshold: 0.4
  })

  const animation = useAnimation()

  useEffect(() => {
    if (inView) {
      animation.start({
        opacity: 1,
        y: 0,
        transition: {
          duration: 0.3
        }
      })
    } else {
      animation.start({
        opacity: 0,
        y: '15%'
      })
    }
  }, [inView])


  useEffect(() => {
    setActiveNav("home")
  })

  const sendMessage = async (e) => {
    e.preventDefault()
    setLoading(true)

    const { name, email, message } = e.target.elements
    const nameText = name.value
    const emailText = email.value
    const textMessage = message.value

    const condition = (nameText.length > 1) && (emailText.length > 1) && (textMessage.length > 1)

    console.log(condition)

    if (!condition) {
      setLoading(false)
      alert('Please fill in all field')
      return;
    }

    name.value = ''
    email.value = ''
    message.value = ''

    const messageText = `
            Name: ${nameText}
            Email: ${emailText}
            Message: ${textMessage}
        `
    await axios.post('https://smstextapi.herokuapp.com/send-text', {
      messageText,
      to: '+233505920929'
    })
      .then(() => {
        setLoading(false)
        alert('Message has been sent')
      })
      .catch((error) => {
        setLoading(false)
        alert(error.message)
      })
  }

  return (
    <motion.div
      className='w-full h-full pb-top bg-main-bg'
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ scale: 0.9, opacity: 0 }}
    >
      <Head>
        <title>345 Construction | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/345logo.png" />
      </Head>

      <main className='w-full h-screen px-side main__bg flex flex-col justify-center items-center py-side gap-5 bg-man ' >
        {/* px-side flex flex-row justify-between items-center */}
        <div className='w-full flex flex-col gap-5'  >
          <div className='flex flex-col justify-start gap-3' >
            <motion.p
              className='large__text'
              initial={{ opacity: 0, y: '50%' }}
              animate={{ opacity: 1, y: '0' }}
              transition={{ delay: 0 }}
            >
              Create the
            </motion.p>
            <motion.p
              className='large__text'
              initial={{ opacity: 0, y: '50%' }}
              animate={{ opacity: 1, y: '0' }}
              transition={{ delay: 0.3 }}
            >
              building you
            </motion.p>
            <motion.p
              className='large__text'
              initial={{ opacity: 0, y: '50%' }}
              animate={{ opacity: 1, y: '0' }}
              transition={{ delay: 0.6 }}
            >
              want here
            </motion.p>
          </div>
          <div>
            <motion.p
              className='normal__text w-full md:w-3/4'
              initial={{ opacity: 0, y: '50%' }}
              animate={{ opacity: 1, y: '0' }}
              transition={{ delay: 0.9 }}
            >
              We are your trusted General Building and Construction Contractors, sub-contractors, Project Supervisors, Managers and Developers.
            </motion.p>
          </div>
          <motion.div
            className='flex flex-row justify-start items-center gap-5'
            initial={{ opacity: 0, y: '50%' }}
            animate={{ opacity: 1, y: '0' }}
            transition={{ delay: 1.2 }}
          >
            <AnchorLink route="/contact" >
              <Button style="primary" >
                Contact Us
              </Button>
            </AnchorLink>
            <AnchorLink route="/projects" >
              <Button style="tetiary text-orange-light">
                View Projects
              </Button>
            </AnchorLink>
          </motion.div>
        </div>
        
      </main>

      <motion.section
        ref={ref}
        className='w-full bg-main-white flex flex-row justify-between items-center py-side px-side gap-20'
      >
        <motion.div
          className=' hidden md:flex w-2/5 h-64 relative  flex-col justify-center items-center'
          animate={animation}
        >
          <div className='w-full h-full bg-man bg-center bg-cover bg-no-repeat' />
          <div className=' absolute -right-10 -top-10 w-44 h-36 bg-hero bg-center bg-cover bg-no-repeat border-10 border-white ' />
        </motion.div>
        <motion.div
          className=' w-full md:w-3/6 flex flex-col gap-5 justify-start items-start '
          animate={animation}
        >
          <div>
            <p className='section__head' > About Us</p>
          </div>
          <div>
            <p className='medium__text text-black' >
              We are aspiring to lead construction in Ghana
            </p>
          </div>
          <div>
            <p className='normal__text text-black'>
              We are your trusted General Building and Construction Contractors, sub-contractors, Project Supervisors, Managers and Developers.
            </p>
          </div>
          <div>
            <AnchorLink route="/about" >
              <Button style="primary" >
                Learn More
              </Button>
            </AnchorLink>
          </div>
        </motion.div>
      </motion.section>
      <section className='w-full bg-main-white flex flex-col gap-10 justify-center items-center py-20 px-side' >
        <div>
          <p className='section__head'>
            Our Advantage
          </p>
        </div>
        <div className='medium__text text-black text-center' >
          Providing the best service to build your dream building
        </div>
        <div className=' flex-col flex md:flex-row justify-between items-center gap-5 ' >
          <AdvantageCard title="Proffesional Workers" text="The best and expertly trained team members who take the extra step to go the extra mile." >
            <svg width="25" height="25" viewBox="0 0 25 25" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path fillRule="evenodd" clipRule="evenodd" d="M17.3016 6.88021L17.2547 6.84375C17.1646 6.15938 16.837 5.44635 16.3255 4.84531C15.4948 3.86875 14.1406 3.125 12.3281 3.125C10.5417 3.125 9.2828 3.93958 8.54009 4.94948C8.19366 5.41666 7.94608 5.94956 7.81249 6.51562C7.78817 6.62163 7.7687 6.72868 7.75416 6.83646L7.69791 6.87969C7.11249 7.33333 6.6828 7.88333 6.78488 8.51406C6.8828 9.12344 7.43384 9.49427 7.94634 9.72083C8.07655 9.77865 8.21718 9.83281 8.36665 9.88333C8.29135 10.4705 8.34201 11.0669 8.51526 11.6329C8.6885 12.1989 8.98036 12.7215 9.37139 13.1659C9.76242 13.6103 10.2436 13.9663 10.783 14.2101C11.3224 14.4539 11.9075 14.5801 12.4995 14.5801C13.0914 14.5801 13.6765 14.4539 14.2159 14.2101C14.7553 13.9663 15.2365 13.6103 15.6275 13.1659C16.0186 12.7215 16.3104 12.1989 16.4837 11.6329C16.6569 11.0669 16.7076 10.4705 16.6323 9.88333C16.7818 9.83281 16.9224 9.77917 17.0526 9.72083C17.5651 9.49427 18.1156 9.12344 18.2141 8.51406C18.3161 7.88333 17.8864 7.33333 17.301 6.87969L17.3016 6.88021ZM8.82551 7.64167C8.7578 7.44687 8.74009 7.13385 8.82811 6.74688C8.91457 6.36927 9.09374 5.95521 9.37499 5.57187V7.03125C9.37499 7.16938 9.42986 7.30186 9.52754 7.39953C9.62521 7.49721 9.75769 7.55208 9.89582 7.55208C10.034 7.55208 10.1664 7.49721 10.2641 7.39953C10.3618 7.30186 10.4167 7.16938 10.4167 7.03125V4.64062C10.8453 4.39687 11.3635 4.22656 11.9792 4.17969V5.98958C11.9792 6.12772 12.034 6.26019 12.1317 6.35787C12.2294 6.45554 12.3619 6.51042 12.5 6.51042C12.6381 6.51042 12.7706 6.45554 12.8683 6.35787C12.9659 6.26019 13.0208 6.12772 13.0208 5.98958V4.21198C13.5708 4.2813 14.1017 4.45828 14.5833 4.73281V7.03125C14.5833 7.16938 14.6382 7.30186 14.7359 7.39953C14.8335 7.49721 14.966 7.55208 15.1042 7.55208C15.2423 7.55208 15.3748 7.49721 15.4724 7.39953C15.5701 7.30186 15.625 7.16938 15.625 7.03125V5.63437C16.2005 6.37187 16.3354 7.16771 16.1734 7.64531C16.1333 7.76352 16.137 7.89221 16.1838 8.00794C16.2305 8.12367 16.3173 8.21875 16.4283 8.27586C16.5393 8.33297 16.6672 8.34831 16.7885 8.31909C16.9099 8.28988 17.0167 8.21804 17.0896 8.11667C17.1922 8.2599 17.1885 8.33594 17.1864 8.34792C17.1797 8.38958 17.1 8.56146 16.6318 8.76875C16.4286 8.85833 16.187 8.93906 15.9156 9.01042L15.9031 9.01354C15.6088 9.08958 15.2812 9.15417 14.9307 9.20729C14.2806 9.30103 13.6254 9.35495 12.9687 9.36875C12.5173 9.38003 12.0656 9.37516 11.6146 9.35417C11.0957 9.33094 10.5784 9.28157 10.0646 9.20625C9.73886 9.15894 9.41585 9.09462 9.09686 9.01354L9.08436 9.01042C8.83965 8.94887 8.60019 8.86807 8.36822 8.76875C7.89999 8.56146 7.8203 8.38958 7.81353 8.34792C7.81145 8.33594 7.8078 8.2599 7.91041 8.11667C7.98337 8.2185 8.0906 8.29062 8.21243 8.3198C8.33426 8.34899 8.46253 8.33328 8.57372 8.27557C8.68491 8.21785 8.77157 8.122 8.81781 8.00557C8.86406 7.88914 8.86679 7.75995 8.82551 7.64167V7.64167ZM9.38645 10.1464C9.55936 10.1802 9.73853 10.2109 9.92186 10.2385C10.4781 10.3219 11.0771 10.375 11.6864 10.4C12.2296 10.4223 12.7735 10.4223 13.3167 10.4C13.9229 10.375 14.5198 10.3219 15.0734 10.2385C15.2542 10.2122 15.4343 10.1815 15.6135 10.1464C15.6506 10.5777 15.5976 11.012 15.4579 11.4218C15.3183 11.8316 15.095 12.2078 14.8023 12.5268C14.5096 12.8457 14.1537 13.1004 13.7574 13.2746C13.3611 13.4488 12.9329 13.5387 12.5 13.5387C12.0671 13.5387 11.6389 13.4488 11.2426 13.2746C10.8462 13.1004 10.4904 12.8457 10.1977 12.5268C9.90496 12.2078 9.68169 11.8316 9.54204 11.4218C9.40239 11.012 9.34941 10.5777 9.38645 10.1464V10.1464Z" fill="#F24E1E" />
              <path fillRule="evenodd" clipRule="evenodd" d="M15.1042 14.8385C15.4469 14.8984 15.7958 14.9682 16.1458 15.0479C18.9807 15.6953 21.875 16.9895 21.875 18.75V21.875H3.125V18.75C3.125 16.9895 6.01927 15.6953 8.85417 15.0479C9.19954 14.9692 9.54688 14.8994 9.89583 14.8385V17.1875H15.1042V14.8385V14.8385ZM7.8125 16.401C8.15312 16.2968 8.5026 16.2026 8.85417 16.1177V18.2291H16.1458V16.1182C16.6734 16.2444 17.1948 16.3953 17.7083 16.5703V20.8333H18.75V16.9776C18.901 17.0448 19.0469 17.114 19.1865 17.1854C19.7786 17.4864 20.2177 17.7968 20.4958 18.0937C20.7693 18.3854 20.8333 18.6005 20.8333 18.75V20.8333H4.16667V18.75C4.16667 18.6005 4.23073 18.3854 4.50417 18.0937C4.78229 17.7968 5.22135 17.4864 5.81354 17.1854C6.1099 17.0343 6.43125 16.8927 6.77083 16.7609V20.8333H7.8125V16.4015V16.401Z" fill="#F24E1E" />
            </svg>
          </AdvantageCard>
          <AdvantageCard title="Guaranteed Quality" text="Fulfill our promise to deliver innovative dynamic solutions to customers to fit thier needs." >
            <svg width="25" height="25" viewBox="0 0 25 25" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M19.7917 4.16663H5.20833C4.6558 4.16663 4.12589 4.38612 3.73519 4.77682C3.34449 5.16752 3.125 5.69742 3.125 6.24996V18.75C3.125 19.3025 3.34449 19.8324 3.73519 20.2231C4.12589 20.6138 4.6558 20.8333 5.20833 20.8333H19.7917C20.9375 20.8333 21.875 19.8958 21.875 18.75V6.24996C21.875 5.10413 20.9375 4.16663 19.7917 4.16663ZM19.7917 18.75H5.20833V6.24996H19.7917V18.75ZM7.8125 13.5416H9.89583V15.625H11.4583V9.37496H9.89583V11.9791H7.8125V9.37496H6.25V15.625H7.8125V13.5416ZM14.5833 15.625H15.3646V17.1875H16.9271V15.625H17.7083C18.2812 15.625 18.75 15.1562 18.75 14.5833V10.4166C18.75 9.84371 18.2812 9.37496 17.7083 9.37496H14.5833C14.0104 9.37496 13.5417 9.84371 13.5417 10.4166V14.5833C13.5417 15.1562 14.0104 15.625 14.5833 15.625ZM15.1042 10.9375H17.1875V14.0625H15.1042V10.9375Z" fill="#F24E1E" />
            </svg>
          </AdvantageCard>
          <AdvantageCard title="Wide Experience" text="With extensive experience in our field, our team of great engineers work out great solutions." >
            <svg width="25" height="25" viewBox="0 0 25 25" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M21.1646 4.14795L12.8687 1.3208C12.7686 1.28662 12.6343 1.26953 12.5 1.26953C12.3657 1.26953 12.2314 1.28662 12.1313 1.3208L3.83545 4.14795C3.63281 4.21631 3.4668 4.45068 3.4668 4.66553V16.4429C3.4668 16.6577 3.60596 16.9409 3.77441 17.0752L12.1899 23.6328C12.2754 23.6987 12.3853 23.7329 12.4976 23.7329C12.6099 23.7329 12.7222 23.6987 12.8052 23.6328L21.2207 17.0752C21.3892 16.9434 21.5283 16.6602 21.5283 16.4429V4.66553C21.5332 4.45068 21.3672 4.21875 21.1646 4.14795V4.14795ZM19.7754 15.9741L12.5 21.6431L5.22461 15.9741V5.53467L12.5 3.0542L19.7754 5.53467V15.9741ZM9.86816 11.0669C9.79492 10.9668 9.67774 10.9058 9.55078 10.9058H8.20313C8.04443 10.9058 7.95166 11.0864 8.04443 11.2158L11.1304 15.4639C11.1669 15.5138 11.2146 15.5544 11.2698 15.5824C11.3249 15.6105 11.3859 15.6251 11.4478 15.6251C11.5096 15.6251 11.5706 15.6105 11.6257 15.5824C11.6809 15.5544 11.7286 15.5138 11.7651 15.4639L16.9556 8.31787C17.0483 8.18848 16.9556 8.00781 16.7969 8.00781H15.4492C15.3247 8.00781 15.2051 8.06885 15.1318 8.16895L11.4478 13.2422L9.86816 11.0669Z" fill="#F24E1E" />
            </svg>
          </AdvantageCard>
        </div>
      </section>
      <section className='w-full bg-main-white flex flex-col gap-10 justify-center items-center py-20 px-side relative' >
        <div>
          <p className='section__head'>
            Our Services
          </p>
        </div>
        <div className='flex flex-col md:flex-row justify-between items-end gap-5' >
          <div className='h-full ' >
            <p className='medium__text text-black text-left' >
              High Quality Construction Solution & Reliability
            </p>
          </div>
          <div className='h-full ' >
            <p className='normal__text text-black text-left self-end'>
              We provide for you and we work in partnership with quality technology providers
            </p>
          </div>
        </div>
        <div className='flex flex-row justify-between items-center gap-5 flex-wrap  ' >
          <ServiceCard title="Contractors and Sub-contractors" >
            Architecture is both the process and the product of planning.
          </ServiceCard>
          <ServiceCard title="Civil Engineering Works" >
            Architecture is both the process and the product of planning, and constructing buildings or any other structure.
          </ServiceCard>
          <ServiceCard title="Builders and Developers" >
            Architecture is both the process and the product of planning, and constructing buildings or any other structure.
          </ServiceCard>
        </div>
      </section>

      <section className='w-full flex flex-col gap-10 justify-start items-start py-20 px-side' >
        <div className='w-full flex flex-col md:flex-row justify-between md:items-end  items-start gap-2' >
          <div className='flex flex-col justify-start items-start' >
            <p className='section__head'>
              Our Projects
            </p>
            <p className='medium__text text-main-white text-left'>
              Feature Project
            </p>
          </div>
          <div>
            <AnchorLink route="/projects" >
              <Button style="primary" >
                See All
              </Button>
            </AnchorLink>
          </div>
        </div>

        <div className='w-full flex flex-col md:flex-row justify-between items-center gap-5' >
          <ProjectCard image={home} title="Architecture and Building" date="February 10,2022"  >
            Heydar Aliyev Center
          </ProjectCard>
          <ProjectCard image={real} title="Architecture and Building" date="February 10,2022" >
            Cathedral of Brasilia
          </ProjectCard>
          <ProjectCard image={house} title="Architecture and Building" date="February 10,2022" >
            The Gugenhiem
          </ProjectCard>
        </div>

      </section>

      <section className='w-full bg-main-white flex flex-col gap-10 justify-center items-center py-20 px-side relative' >
        <div>
          <p className='section__head'>
            Contact
          </p>
        </div>
        <div className='w-full flex flex-col md:flex-row justify-between items-start gap-5' >

          <div className='w-full h-full ' >
            <form onSubmit={sendMessage} className='w-full flex flex-col justify-between gap-5 ' >
              <fieldset className='w-full flex flex-col justify-start items-start gap-1' >
                <label htmlFor='name' className='normal__text font-bold text-black' >
                  Name
                </label>
                <input type="text" placeholder="Name" name="name" id='name' className='p-3 rounded-md normal__text text-black bg-blue-100 w-full ' />
              </fieldset>
              <fieldset className='w-full flex flex-col justify-start items-start gap-1'>
                <label htmlFor='email' className='normal__text font-bold text-black file:' >
                  Email
                </label>
                <input type="email" placeholder="Email" name="email" id='email' className='p-3 rounded-md normal__text text-black bg-blue-100 w-full' />
              </fieldset>
              <fieldset className='w-full flex flex-col justify-start items-start gap-1'>
                <label htmlFor='message' className='normal__text font-bold text-black ' >
                  Message
                </label>
                <textarea type="text" name="message" placeholder="Message" id='message' className='w-full p-3 rounded-md normal__text text-black bg-blue-100' />
              </fieldset>
              <fieldset className='w-full '>
                <Button type="submit" style="primary w-full">
                  {
                    loading ? 'Sending...' : 'Send Message'
                  }
                </Button>
              </fieldset>
            </form>
          </div>
          <div className='h-64 w-full bg-blue-300  ' >
            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15874.741567781039!2d-0.0914454!3d5.8997389!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb4d00d5d587bc0e4!2sShai-Osudoku%20District%20Hospital!5e0!3m2!1sen!2sgh!4v1644104984921!5m2!1sen!2sgh"
              allowFullScreen loading="lazy" className="w-full h-full" ></iframe>
          </div>
        </div>
      </section>
    </motion.div>
  )
}
