import React, { useEffect, useContext } from 'react'
import { motion } from 'framer-motion'
import Head from 'next/head'
import ProjectCard from '../src/Components/ProjectCard'
import { NavContext } from '../src/Components/Context'
import home from '../public/home.jpg'
import house from '../public/house.jpg'
import real from '../public/real-house.jpg'

function projects() {

    const [activeNav, setActiveNav] = useContext(NavContext)

    useEffect(() => {
        setActiveNav("projects")
    })

    return (
        <motion.div
            className='w-full h-full pb-top bg-main-bg'
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ scale: 0.9, opacity: 0 }}
        >
            <Head>
                <title>345 Construction | Projects</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/345logo.png" />
            </Head>
            <main className='w-full h-half px-side flex flex-col justify-center items-center gap-5  bg-plan main__bg' >
                <motion.p
                    className='page__title'
                    initial={{ opacity: 0, y: '50%' }}
                    animate={{ opacity: 1, y: '0' }}
                    transition={{ delay: 0 }}
                >
                    Projects
                </motion.p>
                <motion.p
                    className='medium__text text-center text-main-white'
                    initial={{ opacity: 0, y: '50%' }}
                    animate={{ opacity: 1, y: '0' }}
                    transition={{ delay: 0.3 }}
                >
                    We are multi-construction contractors and clever with a variety of services
                </motion.p>
            </main>
            <motion.section
                className='w-full bg-main-white px-side'
                initial={{ opacity: 0, y: '15%' }}
                animate={{ opacity: 1, y: '0' }}
                transition={{ delay: 0.6 }}
            >
                <div className='w-full flex flex-col md:flex-row justify-between items-center gap-5 py-side ' >
                    <ProjectCard image={home} title="Architecture and Building" date="February 10,2022" >
                        Heydar Aliyev Center
                    </ProjectCard>
                    <ProjectCard image={real} title="Architecture and Building" date="February 10,2022" >
                        Cathedral of Brasilia
                    </ProjectCard>
                    <ProjectCard image={house} title="Architecture and Building" date="February 10,2022" >
                        The Gugenhiem
                    </ProjectCard>
                </div>
            </motion.section>
        </motion.div>
    )
}

export default projects