import React, { useEffect, useContext } from 'react'
import { motion } from 'framer-motion'
import Head from 'next/head'
import ServiceCard from '../src/Components/ServiceCard'
import { NavContext } from '../src/Components/Context'

const services = () => {

    const [activeNav, setActiveNav] = useContext(NavContext)

    useEffect(() => {
        setActiveNav("services")
    })

    return (
        <motion.div
            className='w-full h-full pb-top bg-main-bg'
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ scale: 0.9, opacity: 0 }}
        >
            <Head>
                <title>345 Construction | Services</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='w-full h-half px-side pt-20 pb-5 md:pt-0 flex flex-col justify-center items-center gap-5 bg-head main__bg ' >
                <motion.p
                    className='page__title w-full '
                    initial={{ opacity: 0, y: '50%' }}
                    animate={{ opacity: 1, y: '0' }}
                    transition={{ delay: 0 }}
                >
                    Our Services
                </motion.p>
                <motion.p
                    className='medium__text text-center text-main-white'
                    initial={{ opacity: 0, y: '50%' }}
                    animate={{ opacity: 1, y: '0' }}
                    transition={{ delay: 0.3 }}
                >
                    We are multi-construction contractors and clever with a variety of services
                </motion.p>
            </main>
            <motion.section
                className='w-full bg-main-white px-side'
                initial={{ opacity: 0, y: '15%' }}
                animate={{ opacity: 1, y: '0' }}
                transition={{ delay: 0.6 }}
            >
                <div className='flex flex-row justify-between items-center gap-5 flex-wrap py-side ' >
                    <ServiceCard title="Contractors and Sub-contractors" />
                    <ServiceCard title="Civil Engineering Works" />
                    <ServiceCard title="Builders and Developers" />
                    <ServiceCard title="Project Management" />
                    <ServiceCard title="Project Consultants and Advisors" />
                    <ServiceCard title="Clients Representative Expert" />
                    <ServiceCard title="Negotiators of Properties for CLients" />
                </div>
            </motion.section>
        </motion.div>
    )
}

export default services